name: test_project
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #To use bloc
  flutter_bloc: ^8.1.1
  #For save data
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/xnoyYOGB.png
    - assets/zJXaVrly.png
  uses-material-design: true
